.travis.yml, fastlane/Fastfile, tests/HUBDefaultImageLoaderTests.m
No token is required on Travis-CI.
=> Run codecov on Travis-CI

.gitignore, .travis.yml, HubFramework.xcodeproj/project.pbxproj, codecov.yml, fastlane/Fastfile, fastlane/actions/codecov.rb
Tweaking our codecov config a bit as well as trying to make our CI more stable. Attempting to rid ourselves of “Error 65”.
=> Codecov and build system tweaks

sources/HUBViewControllerImplementation.m
Some methods were accidentally placed under the `UIViewController` pragma mark, which would indicate that they are overrides from the superclass.
Those methods have now been moved to the `Private utilities` pragma mark instead.
=> View controller: Re-order misplaced methods

sources/HUBAutoEquatable.h
=> Fix typo in HUBAutoEquatable

documentation/Component programming guide.md, documentation/Getting started guide.md, documentation/Setup guide.md
Looks like some internal URLs snuck out. 😛
=> Use GitHub relative URLs

sources/HUBViewControllerImplementation.m, tests/HUBViewControllerTests.m, tests/mocks/HUBComponentMock.h, tests/mocks/HUBComponentMock.m
Notify components confirming to HUBComponentContentOffsetObserver protocol of initial content offset when component appears.
@Goos
=> Initial content offset notification

documentation/Getting started guide.md
Minor typos and a missing bracket
=> Minor typos and a missing bracket

README.md
fix carthage update error: unexpected trailing characters in line
=> fix carthage update error

documentation/Getting started guide.md
Hi, I was following the `Getting started guide` and I noticed few places which can be improved.  There were few lines of code missing and without them it was not possible to implement a new _cities_ feature.
=> `Getting started guide` improvements

documentation/Content programming guide.md
Fix wrong link in HUBComponentModel
=> Fix wrong link in HUBComponentModel

Dangerfile
Small grammar nazi fix from non-native speaker =)
=> Fix typo in Dangerfile warning;

sources/HUBComponentReusePool.m, sources/HUBComponentWrapper.h, sources/HUBComponentWrapper.m, sources/HUBViewControllerImplementation.m, tests/HUBComponentWrapperTests.m
While doing this, I also found a bug in the code - the component wrapper was always sending “Highlighted” to its delegate as part of the `componentWrapper:willUpdateSelectionState:` method. This has now been fixed.
=> Component wrapper: Unit test gesture recognizer touch handling

include/HubFramework/HUBViewController.h, sources/HUBViewControllerImplementation.m, tests/HUBViewControllerTests.m
Update the API to allow us to check for visible header and overlay components too.
=> Support other visible component types

HubFramework.xcodeproj/project.pbxproj, include/HubFramework/HUBComponent.h, include/HubFramework/HUBComponentActionObserver.h, include/HubFramework/HubFramework.h, sources/HUBComponentWrapper.h, sources/HUBComponentWrapper.m, sources/HUBViewControllerImplementation.m, tests/HUBViewControllerTests.m, tests/mocks/HUBComponentMock.h, tests/mocks/HUBComponentMock.m
🚚  Enable components to observe actions https://github.com/spotify/HubFramework/issues/99
=> Enable components to observe actions 

include/HubFramework/HUBViewController.h, sources/HUBViewControllerImplementation.m
In the Spotify app, we want to cancel ongoing selections when a custom gesture recognizer is triggered.
=> View controller: Add API for cancelling an ongoing selection

sources/HUBComponentCollectionViewCell.m
This PR fixes misplaced components on the first run of the application.
=> Fix misplaced components on the first run of the app.

live/sources/SocketClient.swift
- The program will send data async if a Socket wasn’t immediately connected.
- More thorough error messages.
=> Live CLI: Improve error handling

demo/sources/ImageComponent.swift
`UIImageView` is `userInteractionEnabled = false` per default.
=> Demo app: Make image components user intractable

demo/sources/CarouselComponent.swift, include/HubFramework/HUBComponentWithChildren.h, include/HubFramework/HUBViewController.h, sources/HUBCollectionViewLayout.m, sources/HUBComponentWrapper.h, sources/HUBComponentWrapper.m, sources/HUBViewControllerImplementation.m, tests/HUBComponentWrapperTests.m, tests/HUBViewControllerFactoryTests.m, tests/HUBViewControllerTests.m
customData can be sent for component actions, however there was no support to send customData when a child action was performed.
=> customData support added to the child actions

documentation/Content programming guide.md
Depends on https://github.com/spotify/HubFramework/pull/135
Resolves https://github.com/spotify/HubFramework/issues/28
=> Update content programming guide with info about pagination

Dangerfile
Make sure the junit result file is readable before attempting to parse it.
Addresses https://github.com/spotify/HubFramework/issues/149
=> Check the junit file is readable

include/HubFramework/HUBComponentImageData.h, sources/HUBComponentImageDataBuilderImplementation.h, sources/HUBComponentImageDataBuilderImplementation.m, sources/HUBComponentImageDataImplementation.h, sources/HUBComponentImageDataImplementation.m, sources/HUBComponentModelBuilderImplementation.m, tests/HUBComponentImageDataBuilderTests.m, tests/HUBComponentModelTests.m
Add custom data property to component image #134
=> Add custom field to the component image schema

demo/sources/NavigationController.swift, include/HubFramework/HUBViewController.h, sources/HUBViewController.m, tests/HUBViewControllerTests.m
Added method to `HUBViewControllerDelegate` to ask if need to ignore top bar (nav bar + status bar) content inset.
=> Ability to ignore top bar content inset

demo/HubFrameworkDemo.xcodeproj/project.pbxproj, demo/sources/SearchBarComponent.swift, demo/sources/TodoListContentOperation.swift, demo/tests/ReloadUITests.swift
Add a UI test that verifies that a view can be rapidly reloaded without any problems.
To enable this test, the "Todo list" feature in the demo app now has a filter, and the delay of the search bar component can now be customized in a content operation.
=> Add a UI test that verifies reload functionality

documentation/JSON programming guide.md, include/HubFramework/HUBComponentImageData.h, include/HubFramework/HUBComponentImageDataBuilder.h, include/HubFramework/HUBComponentImageDataJSONSchema.h, sources/HUBComponentImageDataBuilderImplementation.h, sources/HUBComponentImageDataBuilderImplementation.m, sources/HUBComponentImageDataImplementation.m, sources/HUBComponentImageDataJSONSchemaImplementation.m, sources/HUBComponentModelBuilderImplementation.m, tests/HUBComponentImageDataBuilderTests.m
- Improve documentation
- Add builder support (both API & JSON)
- Add tests
- Add field to JSON programming guide
Resolves https://github.com/spotify/HubFramework/issues/134
=> HUBComponentImageData: Finish custom data implementation

sources/HUBDefaultComponentLayoutManager.m
The build failed locally on iPhone4s (for example)
=> Cast to CGFloat to fix 32bit builds.

tests/HUBViewModelDiffTests.m
Make sure we run all of our diffing unit tests on both algorithms.
=> Test all diffing algorithms

HubFramework.xcodeproj/project.pbxproj, HubFramework.xcodeproj/xcshareddata/xcschemes/HubFramework-iOS.xcscheme, HubFramework.xcodeproj/xcshareddata/xcschemes/HubFramework.xcscheme
Update project and schemes for Xcode 8.2
Update project and schemes for Xcode 8.2
Update project and schemes for Xcode 8.2
=> Update project and schemes for Xcode 8.2

README.md
More links will follow as we publish more videos
=> README: Add link to Hub Framework Sessions Episode 1

README.md
Episode 2 is now available on YouTube
=> README: Add link to Hubs sessions episode 2

demo/tests/HeaderComponentUITests.swift, tests/HUBComponentModelBuilderTests.m, tests/HUBViewControllerFactoryTests.m, tests/HUBViewControllerTests.m, tests/HUBViewModelBuilderTests.m, tests/HUBViewModelLoaderFactoryTests.m, tests/HUBViewModelLoaderTests.m
Use the shorter `u` form instead of casting explicitly to `NSUInteger`.
=> Use condensed form of unsigned cast.

demo/HubFrameworkDemo.xcodeproj/project.pbxproj, demo/sources/AppDelegate.swift, demo/tests/ReloadUITests.swift, demo/tests/ScrollingUITests.swift, include/HubFramework/HUBViewController.h, sources/HUBViewController.m, tests/HUBViewControllerTests.m
```objc
@property (nonatomic, assign) BOOL bounces;
@property (nonatomic, assign) BOOL alwaysBounceVertical;
```
added to `HUBViewController` to allow controlling if the underlying `UICollectionView` should bounce when scrolled, as well as if it should allow scrolling vertically if content is smaller than the `UICollectionView`'s bounds.
=> Expose bounce controls in HUBViewController

sources/HUBViewModelLoaderImplementation.m, tests/HUBViewModelLoaderTests.m
This reverts commit 4f07e6aa0cbb8b052712d33390ff3b4cc296c7a2.
=> Revert "Delay observing of connectivity state"

HubFramework.xcodeproj/project.pbxproj, sources/HUBViewControllerExperimentalImplementation.h, sources/HUBViewControllerExperimentalImplementation.m, sources/HUBViewControllerFactoryImplementation.m, tests/HUBViewControllerFactoryTests.m
Create an "experimental" (and untested) view controller, and make it available if a feature registers with a `HUBViewController=v2` option.
The experimental view controller is a work-in-progress and is currently an exact line-for-line copy of the "standard" VC.
=> Create experimental view controller implementation

sources/HUBViewControllerExperimentalImplementation.h, sources/HUBViewControllerExperimentalImplementation.m, sources/HUBViewControllerFactoryImplementation.m
We will further develop the experimental VC (or other experimental VCs) to be more modular.
=> Update experimental VC to not use batch updates

HubFramework.xcodeproj/project.pbxproj, HubFramework.xcodeproj/xcshareddata/xcschemes/HubFramework-iOS.xcscheme, HubFramework.xcodeproj/xcshareddata/xcschemes/HubFramework.xcscheme
=> Update project for Xcode 8.3

sources/HUBViewControllerDefaultScrollHandler.m
I missed this in the last review.
=> Change MIN to GLUECGFloatMin

HubFramework.xcodeproj/project.pbxproj
This should fix the issues in #325
@rastersize @cerihughes
=> Disable modules in test targets as well.

demo/sources/NavigationController.swift, include/HubFramework/HUBViewController.h, sources/HUBViewControllerExperimentalImplementation.m, sources/HUBViewControllerImplementation.m, tests/HUBViewControllerImplementationTests.m
=> Adds a delegate method enabling the view controller's delegate to observe when actions are being performed.

include/HubFramework/HUBViewControllerScrollHandler.h
=> Fix nullability of HUBViewControllerScrollHandler

HubFramework.xcodeproj/project.pbxproj, HubFramework.xcodeproj/xcshareddata/xcschemes/HubFramework-iOS.xcscheme, HubFramework.xcodeproj/xcshareddata/xcschemes/HubFramework.xcscheme
Rehash of #353 ,now with a redundant description to pacify Danger.
@dflems @rastersize @krris @cerihughes
=> Update projects for Xcode 9.1

include/HubFramework/HUBComponentModelJSONSchema.h, include/HubFramework/HUBComponentWithChildren.h, include/HubFramework/HUBConfig.h, include/HubFramework/HUBConfigBuilder.h, include/HubFramework/HUBConfigViewControllerFactory.h, include/HubFramework/HUBManager.h, include/HubFramework/HUBViewController.h, include/HubFramework/HUBViewModelJSONSchema.h, include/HubFramework/HubFramework.h, sources/HUBActionHandlerWrapper.h, sources/HUBActionRegistryImplementation.h, sources/HUBComponentImageDataBuilderImplementation.h, sources/HUBComponentRegistryImplementation.h, sources/HUBComponentReusePool.h, sources/HUBComponentWrapper.h, sources/HUBLiveServiceImplementation.h, sources/HUBLiveServiceImplementation.m, sources/HUBViewControllerFactoryImplementation.h
=> Remove invalid/unnecessary forward declarations
