- .cocoadocs.yml
So we get Spotify-y colors. Copied from [SPTDataLoader](https://github.com/spotify/SPTDataLoader/blob/master/.cocoadocs.yml).
@JohnSundell @spotify/objc-dev
> Add configuration of Cocoadocs

- tests/HUBDefaultImageLoaderTests.m
Exploring why the cache test for the image loader fails on travis.
> Enables (and fixes) the image loader caching test

- demo/sources/AppDelegate.swift
- include/HubFramework/HUBManager.h
- sources/HUBManager.m
- tests/HUBDefaultImageLoaderTests.m
- tests/HUBManagerTests.m
Since we want to support a lot of customization options for the Hub Framework (we also need them for the Spotify app), the initializer for `HUBManager` is quite large. However, most of its arguments are optional, so with this change a convenience initializer is added that only takes the required arguments.
Also update the demo app to using this new initializer.
> HUBManager: Add convenience initializer

- demo/HubFrameworkDemo.xcodeproj/project.pbxproj
Hi Spotify team and @JohnSundell! I cloned the repo and tried to build and run the demo app on iOS simulator, but I got the following error. The project under DerivedData is not related to the HubFramework demo project at all:
```
Dependency Analysis Error
Check dependencies
Argument list too long: recursive header expansion failed at /Users/keitaito/Library/Developer/Xcode/DerivedData/test-rbenv-03132016-axujngqvejimbiehvegvqqlckgub/Index/Debug/iphonesimulator9.2-x86_64/test-rbenv-03132016.xcindex.
```
To fix the error, I changed project settings. I removed a path from "Library Search Paths" under "Search Paths" section in "Build Settings". 
```
$(USER_LIBRARY_DIR)/Developer/Xcode/DerivedData (with recursive option)
```
This path is displayed as like this:
``` …
```
> Fix an issue demo app build fails by removing Library Search Paths

- HubFramework.xcodeproj/project.pbxproj
- sources/HUBComponentModelImplementation.m
- sources/HUBKeyPath.h
The `index` selector reference was ambiguous and the build would fail. This change resolves that by introducing a typed and compile time checked key-path to string macro.
> Fix `ignoredAutoEquatablePropertyNames` not compiling for device

- sources/HUBViewModelImplementation.m
Use the newly introduced `HUBKeyPath` macro to return ignored auto equatable property names, instead of using `NSStringFromSelector`.
> View Model: Use HUBKeyPath

- .jazzy.yml
- HubFramework.podspec
Following the release of version `2.0.1`
> Bump Jazzy config & Podspec to 2.0.1

- include/HubFramework/HUBViewModel.h
- include/HubFramework/HUBViewModelBuilder.h
- sources/HUBAutoEquatable.m
- sources/HUBUtilities.h
- sources/HUBViewControllerImplementation.m
- sources/HUBViewModelBuilderImplementation.m
- sources/HUBViewModelImplementation.h
- sources/HUBViewModelImplementation.m
- tests/HUBComponentModelBuilderTests.m
- tests/HUBComponentModelTests.m
- tests/HUBComponentTargetBuilderTests.m
- tests/HUBInitialViewModelRegistryTests.m
- tests/HUBJSONSchemaRegistryTests.m
- tests/HUBViewControllerTests.m
- tests/HUBViewModelBuilderTests.m
- tests/HUBViewModelDiffTests.m
- tests/HUBViewModelLoaderTests.m
- tests/HUBViewModelTests.m
This change adds support for setting a `UINavigationItem` on a `HUBViewModel`, which will then be used when its `HUBViewController` is added to a navigation controller.
This is done by replacing `navigationBarTitle` with `navigationItem` on `HUBViewModel` (since you can now just use the navigation item’s title). No backwards compatibility is added here, since the use cases for using a `HUBViewModel` directly are very small.
However, on the builder (`HUBViewModelBuilder`) backwards compatibility is achieved by letting `navigationBarTitle` be an alias for `navigationItem.title`.
Some equality checking code is extracted from `HUBAutoEquatable` into `HUBUtilities` to avoid code duplication.
> Add support for UINavigationItem

- fastlane/actions/codecov.rb
Use Codecov’s automatic detection code instead. They support the CI environments we run on.
@JohnSundell
> Fix the Codecov branch/PR detection

- sources/HUBCollectionViewLayout.m
- tests/HUBCollectionViewLayoutTests.m
Fixes an issue where the collection view layout wouldn't take the bottom content inset into account when determining the proper offset after updates.
> Fix max target content offset after updates

- sources/HUBComponentWrapper.h
- sources/HUBComponentWrapper.m
- sources/HUBViewControllerImplementation.m
- tests/HUBComponentWrapperTests.m
- tests/HUBViewControllerTests.m
Adds the possibility of child components listening for content offset updates via the `HUBComponentContentOffsetObserver` protocol.
Also changes slightly how the list of eligible components are maintained for base-level components as well, adding and removing them in the `willDisplayCell:` & `didEndDisplayingCell:` callbacks.
Resolves https://github.com/spotify/HubFramework/issues/19
> Content offset updates for child component

- HubFramework.xcodeproj/project.pbxproj
- include/HubFramework/HUBBlockContentOperationFactory.h
- include/HubFramework/HUBViewControllerFactory.h
- sources/HUBBlockContentOperationFactory.m
- sources/HUBViewControllerFactoryImplementation.m
- tests/HUBViewControllerFactoryTests.m
This change adds a new way to create view controllers, without having to pre-register a feature with the framework. The use case for this is to more easily be able to create view controller, which decreases the learning curve to get into using the framework.
It also will make it easier to use the Hub Framework for playgrounds.
To make this happen, another convenience API is introduced to be able to create content operation factories using a concrete class that takes a block. Again, this reduces the barrier of entry for creating content operations, and the need for boilerplate.
> Add API to create view controllers without registering features

- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
UICollectionView’s `performBatchUpdates:` method checks the number of items in the collection view before performing the update block and after that. It expects the following: 
```The number of items contained in an existing section after the update must be equal to the number of items contained in that section before the update, plus or minus the number of items inserted or deleted from that section and plus or minus the number of items moved into or out of that section.```
If we update the view model before performing the batch updates `collectionView:numberOfItemsInSection:` will return the updated count even before the actual update and it will fail after that with uncaught exception `'NSInternalInconsistencyException', reason: 'Invalid update’`. 
For example we have 0 items initially …
> Set the viewModel after performing batch updates

- sources/HUBCollectionViewLayout.m
- tests/HUBCollectionViewLayoutTests.m
This patch fixes a bug that would cause the content offset of a view controller to be incorrect after an initial update, where the view goes from being empty to being populated with components.
The problem was that the topmost visible index would end up being `NSNotFound`, which would make the view jump to the bottom.
> Fix content offset adjustment error when view is empty

- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
This patch fixes a bug where header components wouldn’t be notified of a content offset change when they appear. Body & overlay components already had this intended behavior.
The fix is to merge the “component will appear” logic into a single method, to make sure that all components are treated the same in this regard.
> Notify header component of content offset change when it appears

- include/HubFramework/HubFramework.h
Missed to add it to the umbrella header when it was introduced.
> Umbrella header: Add HUBBlockContentOperationFactory

- sources/HUBComponentCellWrapperView.m
Because of the ways UIKit handles touches in `UITableViewCell` and `UICollectionViewCell`, and we want to support using “orphaned” cells as component views - we need to employ some custom touch handling.
It turns out though, that the custom touch handling wasn’t taking nested touchable views (such as a `UIButton` inside a cell) into account. This has now been fixed, by making sure we only do custom handling when the content view of a cell was touched.
> Support nested touchable views inside a UI[Table/Collection]ViewCell

- HubFramework.xcodeproj/project.pbxproj
Should only be included in library target.
> Remove HUBComponentImageDataBuilderImplementation from test target

- sources/HUBComponentModelBuilderImplementation.m
- tests/HUBComponentModelBuilderTests.m
The bug was only reproducible if there are 4 or more components with preferred index and some components without it, and manifested in incorrect resulting order.  
Fixed by sorting components by preferred index before inserting them at required positions.
@Goos
> Fix bug with incorrect order of components with preferred index.

- HubFramework.podspec
`s.source_files` was referencing a nonexistent directory.
> Fix podspec file

- include/HubFramework/HUBComponentModelBuilder.h
This change makes two APIs on `HUBComponentModelBuilder` a lot nicer to use from Swift, as well as making them adhere to the Swift 3 API guidelines.
Before:
```swift
componentBuilder.forChildWithIdentifier("id")
componentBuilder.removeForChild(withIdentifier: "id")
```
After:
```swift
componentBuilder.builderForChild(withIdentifier: "id")
componentBuilder.removeBuilderForChild(withIdentifier: "id")
```
> Component model builder: Swiftify API

- HubFramework.xcodeproj/project.pbxproj
It’s a fix for not working code completion and syntax highlighting in unit tests.  Based on
https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
Defines Modules should be set to YES.
> Enable code completion and syntax higlighting in unit tests.

- include/HubFramework/HUBComponentModel.h
- include/HubFramework/HUBViewController.h
- sources/HUBComponentModelImplementation.m
- sources/HUBComponentWrapper.h
- sources/HUBComponentWrapper.m
- sources/HUBViewControllerImplementation.m
- tests/HUBComponentModelTests.m
- tests/HUBViewControllerTests.m
This PR:
- Allows a component model to return an `NSIndexPath` representing where it sits in the component hierarchy,
- Updates the `HUBViewController` to return the index paths of all visible body components, not just the top level body components.
> Add basic indexPath support to the component model.

- include/HubFramework/HUBViewController.h
- sources/HUBComponentModelImplementation.m
- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
This change changes the name of the API used to retrieve the currently visible body component views back to the name that was used before https://github.com/spotify/HubFramework/pull/84. We don’t need to change the name of the API because the key type was changed.
This change also adds a bit more thorough documentation for the API, explaining what the API user can expect from the index paths used as keys.
> View controller: Un-rename visible component views API & improve docs

- sources/HUBComponentModelImplementation.m
Instead of storing the indices in reverse order, then iterating in reverse, store them in the order they'll be accessed in.
Also gets around a static analyser warning, which claims we could return `nil` from the method (which wasn't strictly true).
> Simplify the generation of the index path.

- sources/HUBComponentWrapper.m
- tests/HUBViewControllerTests.m
This patch fixes a bug that would cause a HUBViewController’s delegate to be notified of a selection event twice when that selection was triggered programmatically (compared to when the user selects a component through the UI).
The reason the tests weren’t catching this was because the UI wasn’t setup properly before triggering the programmatic selection. This patch also fixes that test.
> Don’t notify delegate twice when performing programmatic selection

- sources/HUBUtilities.h
- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
Solves https://github.com/spotify/HubFramework/issues/82
Send unwrapped `HUBComponentCollectionViewCell` as the view parameter when calling methods on `HUBViewControllerDelegate`.
> Send component's view instead of a collection view cell in HUBViewControllerDelegate.

- sources/HUBComponentWrapper.m
The gesture recognizer used to handle component highlighting and selection prevents buttons inside the component from receiving touches. This PR fixes the issue by not forwarding button touches to the gesture recognizer.
> Component wrapper: fix gesture recognizer stealing button touches

- sources/HUBComponentWrapper.m
Since the new selection handling mechanism was introduced, child components have been made unselectable, because the touch recognizer used to perform selection handling was “stealing touches” from nested views.
This has now been fixed by not using selection handling if one of the following view classes were touched:
- UIButton
- UICollectionViewCell
- UITableViewCell
A more rigid implementation of this would be to check the visible child components and hit test them, but since we’re currently also using plain UIViews as child components, we need to go through the view hierarchy.
> Fix bug causing nested components to be unelectable

- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
This patch fixes a bug where child components would get a `CGSizeZero` container view size, if created before their parent component was resized by `UICollectionView`. This is done by using layout attributes directly when computing the container view size for root body components.
This lookup is very fast (`O(1)`), since we cache the layout attributes by index path.
> Calculate parent component’s view size up-front when creating children

- HubFramework.xcodeproj/project.pbxproj
- sources/HUBViewControllerImplementation.m
- sources/HUBViewModelRenderer.h
- sources/HUBViewModelRenderer.m
Separates the UICollectionView update logic into a separate class – the HUBViewModelRenderer. Also moves the diffing of view models to right before the reload in order to avoid unpredictable behaviour caused by multiple updates happening inbetween a UICollectionView reload.
> Separate UICollectionView update logic and diff only before reloads

- demo/HubFrameworkDemo.xcodeproj/project.pbxproj
- demo/sources/CarouselComponent.swift
- demo/sources/DefaultComponentFactory.swift
- demo/sources/DefaultComponentNames.swift
- demo/sources/PrettyPicturesContentOperation.swift
- demo/sources/RootContentOperation.swift
This change adds a carousel component to the demo app, partly for demonstration purposes - but also to enable us to cheaply perform UI tests and manual verification for a component with children (the demo app previously didn’t have any components with children).
The “Pretty pictures” feature of the demo app is also updated to display a carousel on the top, as well as adding tappable links to the pictures that it displays.
> Demo app: Add carousel component

- include/HubFramework/HUBViewController.h
- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
- tests/mocks/HUBCollectionViewMock.h
- tests/mocks/HUBCollectionViewMock.m
This will enable API users to make decisions based on whether the user is currently scrolling the main content view of a Hub Framework view controller.
> View controller: Add property to inspect whether view is scrolling

- sources/HUBCollectionViewLayout.m
- sources/HUBViewModelDiff.m
- tests/HUBCollectionViewLayoutTests.m
- tests/HUBViewModelDiffTests.m
Changes so that the HUBViewModelDiff calculates updated indices using the previous data model rather than the new one.
@spotify/objc-dev (@cerihughes, @JohnSundell @rastersize)
> Diff updated indexes using old view model

- sources/HUBComponentModelImplementation.m
- tests/HUBComponentModelTests.m
The index path shouldn't be used when considering equality as it uses information about the parent, (which is already excluded from the calculation).
> Don’t compare index path for equality.

- sources/HUBViewModelRenderer.h
- sources/HUBViewModelRenderer.m
- tests/mocks/HUBURLProtocolMock.h
- tests/mocks/HUBURLProtocolMock.m
Blocks in Objective-C are using a syntax similar to C function pointers, so `void (^foo)()` can be called with any parameters (`foo(@"Hub", 42)`), and you can assign blocks accepting any parameters to it (`foo = ^(int i) { … };`.
The type should be `void(^)(void)` to prevent that.
> Cleanup: More concrete block types

- include/HubFramework/HUBViewController.h
- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
This change makes `HUBViewController` send a component’s layout traits to its delegate as part of the methods called whenever a component is either about to appear, or just disappeared from the screen.
The reason for this change is that we want to enable API users to make decisions based on the layout traits, instead of resorting to comparing view frames (which are bound to change during the layout cycle).
> View controller: Send layout traits for component appear/disappear

- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
This patch fixes a bug in the hit testing API `indexOfBodyComponentAtPoint:`, which previously wouldn’t take the content offset of the view into account.
> View controller: Take content offset into account for hit testing

- include/HubFramework/HUBViewController.h
- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
This new API is an alternative to returning **all** visible component views, and provides a much faster (pretty much `O(1)` complexity - if you disregard the length of the index path) way of looking up just a **single** component view.
> View controller: Add API to retrieve a single visible component view

- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
This caused some issues when attempting to scroll somewhere in the initial `viewControllerDidFinishRendering:`-call, as `configureHeaderComponent` would change the content offset _after_ the delegate was notified (as the completion block is called instantly).
> Moves the configuration of header and overlay components when reloading

- demo/sources/GitHubSearchBarContentOperation.swift
- demo/sources/TodoListContentOperation.swift
- documentation/Action programming guide.md
- include/HubFramework/HUBContentOperationActionObserver.h
- sources/HUBViewModelLoaderImplementation.m
- tests/mocks/HUBContentOperationMock.m
🚚  Delivers: https://github.com/spotify/HubFramework/issues/112
We can remove `viewURI` argument because `HUBActionContext` already contains it.
> Remove viewURI argument from HUBContentOperationActionObserver API.

- .travis.yml
- HubFramework.xcodeproj/project.pbxproj
- HubFramework.xcworkspace/contents.xcworkspacedata
- demo/sources/AppDelegate.swift
- fastlane/Fastfile
- include/HubFramework/HUBHeaderMacros.h
- include/HubFramework/HUBLiveService.h
- include/HubFramework/HUBManager.h
- include/HubFramework/HubFramework.h
- live/HubFrameworkLive.xcodeproj/project.pbxproj
- live/sources/AnsiColor.swift
- live/sources/CommandLine.swift
- live/sources/CommandLineResult.swift
- live/sources/Error+Print.swift
- live/sources/FileWatcher.swift
- live/sources/Live.swift
- live/sources/LiveError.swift
- live/sources/SocketClient.swift
- live/sources/String+PrintWithColor.swift
- live/sources/main.swift
- sources/HUBLiveContentOperation.h
- sources/HUBLiveContentOperation.m
- sources/HUBLiveServiceImplementation.h
- sources/HUBLiveServiceImplementation.m
- sources/HUBManager.m
- tests/HUBLiveServiceTests.m
- tests/HUBManagerTests.m
- tests/mocks/HUBInputStreamMock.h
- tests/mocks/HUBInputStreamMock.m
This PR adds live editing capabilites to the Hub Framework. 🎉 This is done through a new `HubFrameworkLive` project that builds a `hublive` command line application, that can then connect to a newly introduced `HUBLiveService` running in a Hub Framework powered application.
**A few notes:**
- The implementation of the `HUBLiveService` API is only compiled if the host application is being compiled for `DEBUG`. This reduces the risk of running into security issues in production code.
- The live editing system is built using `NSNetService` - which is the Apple-provided framework for interacting with the Bonjour local networking system. It uses a socket on a user configurable port.
- Using live is opt-in for applications using the Hub Framework. The live service needs to be explicitly enabled …
> Introduce Live Editing

- documentation/JSON programming guide.md
- include/HubFramework/HUBViewModel.h
- include/HubFramework/HUBViewModelBuilder.h
- include/HubFramework/HUBViewModelJSONSchema.h
- sources/HUBJSONKeys.h
- sources/HUBViewModelBuilderImplementation.m
- sources/HUBViewModelImplementation.h
- sources/HUBViewModelImplementation.m
- sources/HUBViewModelJSONSchemaImplementation.m
- tests/HUBComponentModelTests.m
- tests/HUBInitialViewModelRegistryTests.m
- tests/HUBViewModelBuilderTests.m
- tests/HUBViewModelDiffTests.m
- tests/HUBViewModelTests.m
This property was originally intended to provide a way to paginate content from a backend service, by letting that backend service returning a URL from where additional content can be loaded.
However, since the move to content operations (and with content operation chaining) - this has been made less and less relevant, since content operations are not required to actually load their content from a backend service.
This property wasn’t actually used anywhere in the framework, so removing it in favor of an upcoming new content operation extension API for paginated content.
Relates to https://github.com/spotify/HubFramework/issues/28
> Remove HUBViewModel.extensionURL

- sources/HUBIconImplementation.h
- sources/HUBIconImplementation.m
- tests/HUBIconTests.m
Previously, 2 equivalent `HUBIconImplementation`s would return `NO` for `isEqual:`.
> Implement equality for icons.

- HubFramework.xcodeproj/project.pbxproj
- include/HubFramework/HUBComponentWithChildren.h
- include/HubFramework/HUBComponentWithScrolling.h
- include/HubFramework/HUBScrollPosition.h
- include/HubFramework/HUBViewController.h
- include/HubFramework/HUBViewControllerScrollHandler.h
- include/HubFramework/HubFramework.h
- sources/HUBComponentWrapper.h
- sources/HUBComponentWrapper.m
- sources/HUBViewControllerDefaultScrollHandler.m
- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
- tests/mocks/HUBComponentMock.h
- tests/mocks/HUBComponentMock.m
- tests/mocks/HUBViewControllerScrollHandlerMock.h
- tests/mocks/HUBViewControllerScrollHandlerMock.m
Putting this up as work-in-progress for discussion purposes! 
This PR adds the possibility of scrolling to nested children. 
The first challenge with doing this is that the HubFramework doesn't really know anything about how its children handles _their_ children, which forces us to delegate that to the components themselves. 
The second challenge is animations – since the components are reported to the HubFramework when they are visible, we have to wait for the animations to finish each step along the way.
@JohnSundell, @cerihughes, @spotify/objc-dev
> Adds possibility of scrolling to indexpaths (children included) to the HUBViewController.

- spotify_os.xcconfig
When using xcode 8.1 you get a number of partial-availability and double-promotion build errors. Looks like you guys are just ignoring them like this?
> add ignored warnings for xcode 8.1 as well

- spotify_os.xcconfig
Since the beta is out it’d be nice to make the framework work with it 😋
Like the recently merged PR but also for Xcode 8.2.
> Ignore warnings for Xcode 8.2

- HubFramework.xcodeproj/project.pbxproj
- include/HubFramework/HUBContentOperationWithPaginatedContent.h
- include/HubFramework/HUBViewModelLoader.h
- sources/HUBContentOperationExecutionInfo.h
- sources/HUBContentOperationExecutionInfo.m
- sources/HUBContentOperationWrapper.h
- sources/HUBContentOperationWrapper.m
- sources/HUBViewModelLoaderImplementation.m
- tests/HUBViewModelLoaderTests.m
- tests/mocks/HUBContentOperationMock.h
- tests/mocks/HUBContentOperationMock.m
This change introduces an API for appending paginated content to a view model. By making a content operation conform to `HUBContentOperationWithPaginatedContent`, new content can now be added to an existing view model builder.
To support the declarative nature of the Hub Framework, content operations are always guaranteed to execute from a “clean state”. `HUBViewModelLoader` keeps snapshots of previous view model builders & errors, to be able to make this guarantee.
However, with pagination, we don’t want to execute from a clean state. Instead, we want to append content to the **current** state, which imposes some interesting challenges on the content loading code.
To accommodate these 2 different uses cases, a new `HUBContentOperationExecutionInfo` is introduced. Instead of enqueueing …
> View model loader: Support appending paginated content

- sources/HUBViewControllerImplementation.m
The issue:
- For a brief moment, the view was shown without header and overlay components even though the model had them. 
Fix:
- configuring the overlay and header before the model is rendered
> HeaderView and Overlay components are now configured before the viewmodel is rendered

- sources/HUBContainerView.h
- sources/HUBContainerView.m
- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
Make HubContainerView set background color only for the collection view it contains instead of overriding background color of all the subviews.
> Fix components background color gets overridden when added to HubContainerView

- sources/HUBContainerView.h
- sources/HUBContainerView.m
- sources/HUBViewControllerImplementation.m
This change moves the gesture recognizer used for pan (scroll) events in the collection view to the view level. This is done in order to support scrolling on a header or overlay component, without having to resort to manual -pointInside checks.
> View controller: Recognize pan gestures on a view level

- demo/HubFrameworkDemo.xcodeproj/project.pbxproj
- demo/sources/ReallyLongListContentOperation.swift
- demo/tests/PaginationUITests.swift
- demo/tests/SelectionUITests.swift
- include/HubFramework/HUBContentOperationWithPaginatedContent.h
- include/HubFramework/HUBViewModelLoader.h
- include/HubFramework/HubFramework.h
- sources/HUBViewControllerImplementation.m
- sources/HUBViewModelLoaderImplementation.m
- tests/HUBViewControllerTests.m
- tests/HUBViewModelLoaderTests.m
- tests/mocks/HUBComponentFactoryMock.h
- tests/mocks/HUBComponentFactoryMock.m
This pull request integrates the pagination mechanism introduced in https://github.com/spotify/HubFramework/pull/132 into `HUBViewController`. Whenever the user is about to scroll to the bottom of a view, the next page of content is automatically loaded.
The "Really Long List" feature in the demo app has also been rewritten to support this new pagination feature, instead of having to perform work on a background thread.
Implements the view controller part of https://github.com/spotify/HubFramework/issues/28. Will not close the issue until the content programming guide has been updated :)
> Pagination: Integrate with view controller

- HubFramework.xcodeproj/project.pbxproj
- sources/HUBCollectionViewFactory.m
- tests/HUBCollectionViewFactoryTests.m
The collection view factory is used to provide collection view to the`HUBViewControllerImplementation` class. The accessibility identifier could be used for automated UI tests.
> Add accessibility identifier to the collection view

- HubFramework.xcodeproj/project.pbxproj
- include/HubFramework/HUBViewController.h
- sources/HUBCollectionView.h
- sources/HUBCollectionView.m
- sources/HUBCollectionViewFactory.m
- sources/HUBViewControllerImplementation.m
- tests/HUBCollectionViewFactoryTests.m
- tests/HUBViewControllerTests.m
- tests/mocks/HUBCollectionViewFactoryMock.h
- tests/mocks/HUBCollectionViewFactoryMock.m
- tests/mocks/HUBCollectionViewMock.h
This change adds a new delegate method for `HUBViewController` that gets called every time the user is about to start scrolling a view. The delegate then has an opportunity to veto wether the scroll event should start.
> View controller: Add API to disable scrolling

- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
Removes the calls to the scroll handler when scrolling programmatically with the `scrollToComponentOfType:...`-method. This is done to be more in line with the UICollectionView / UIScrollView interfaces, where the scrolling methods don't call the same delegate methods as scrolling by hand.
@spotify/objc-dev, @JohnSundell
> Removes the calls to the scroll handler when scrolling manually

- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
Similar to how we deal with body components (with diffing), there’s no need to reconfigure a header or overlay component if it’s going to serve the exact same model as its currently serving.
> View controller: Don’t reconfigure header/overlay components serving the same model

- sources/HUBViewControllerImplementation.m
Fixes a potential crash in the `frameForBodyComponentAtIndex:`-call as the bounds checking was done with the number of components in the view model rather than the collection view.
@spotify/objc-dev, @JohnSundell, @cerihughes
> Fixes a potential crash in `frameForBodyComponentAtIndex:`

- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
- tests/mocks/HUBViewControllerScrollHandlerMock.h
- tests/mocks/HUBViewControllerScrollHandlerMock.m
Adds another check for the content inset once the view model finishes rendering, as the recent move of header configuration introduced an inconcistency for scroll handlers where the content inset was dependant on the size of content (e.g. component frames).
@spotify/objc-dev, @cerihughes, @JohnSundell
> Update content inset once the view model finishes rendering

- tests/HUBComponentWrapperTests.m
- tests/HUBDefaultImageLoaderTests.m
- tests/HUBViewControllerTests.m
`XCTestExpectation` is a bit dangerous since it might crash the test if it’s fulfilled after `waitForExpectationWithTimeout:handler:` times out. The workaround is to make the variable referencing the expectation weak. So that it goes away and the `-fulfill` message is instead sent to `nil`.
> Fix potential crashers in unit tests

- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
I noticed that the appearance delegate is notified only when body components are displayed. I added the same logic for other types of components like headers and overlays.
> Notify delegate when overlay and header components appear

- include/HubFramework/HUBComponentRegistry.h
- sources/HUBCollectionViewLayout.h
- sources/HUBCollectionViewLayout.m
- sources/HUBComponentRegistryImplementation.h
- sources/HUBComponentReusePool.h
- sources/HUBComponentReusePool.m
- sources/HUBViewControllerImplementation.h
- sources/HUBViewControllerImplementation.m
This change is part of the work for https://github.com/spotify/HubFramework/issues/158, which has the end goal of making `HUBViewController` publicly initializable. To do this, we need to remove all dependencies on concrete internal classes.
With this, the API to create new component instances has been moved from `HUBComponentRegistryImplementation` to the `HUBComponentRegistry` API. While it’s not expected that any API user will use this method directly, it enables the view controller to not rely on the concrete component registry implementation.
> View controller: Use component registry as HUBComponentRegistry protocol

- demo/HubFrameworkDemo.xcodeproj/project.pbxproj
- demo/tests/NavigationItemUITests.swift
Tests that `rightBarButtonItem`s that are configured through the model builder appear and are tappable.
> Add a UI test for navigation items

- HubFramework.xcodeproj/project.pbxproj
- sources/HUBActionHandlerWrapper.h
- sources/HUBActionHandlerWrapper.m
- sources/HUBAsyncActionWrapper.h
- sources/HUBAsyncActionWrapper.m
- sources/HUBViewControllerImplementation.h
- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerTests.m
This change is part of the work for https://github.com/spotify/HubFramework/issues/158, which has the end goal of making `HUBViewController` publicly initializable. To do this, we need to remove all dependencies on concrete internal classes.
This is the first step, which makes `HUBViewController` take any `HUBActionHandler` as part of its initializer, rather than relying on the concrete `HUBActionHandlerWrapper` implementation. To make this happen, logic that was previously delegated to the view controller around chaining of async actions needed to be moved into the action handler wrapper itself.
The test change that was made in `HUBViewControllerTests` needed to make made to avoid implicit autorelease pools from taking over the lifecycle of objects.
> Use HUBActionHandlerWrapper as HUBActionHandler protocol

- include/HubFramework/HUBViewController.h
- sources/HUBViewControllerImplementation.m
- spotify_os.xcconfig
- tests/HUBViewControllerTests.m
Changes the callback in the `scrollToComponentOfType:indexPath:scrollPosition:animated:completion:` so that it is called when each step of the scrolling is completed, rather than once after all the steps.
> Changes how the completion handler in the scrolling method is called.

- sources/HUBViewControllerImplementation.m
Solves that when a hub view controller is presented while an app is in the background, the collectionview layout asserts on app foregrounding.
@Goos @JohnSundell
> Fix layout crash when a hub feature is presented while backgrounded

- HubFramework.xcodeproj/project.pbxproj
- demo/sources/AppDelegate.swift
- documentation/Live editing guide.md
- include/HubFramework/HUBLiveService.h
- include/HubFramework/HUBViewController.h
- include/HubFramework/HUBViewControllerFactory.h
- include/HubFramework/HUBViewControllerScrollHandler.h
- sources/HUBLiveServiceImplementation.m
- sources/HUBViewController+Initializer.h
- sources/HUBViewController.m
- sources/HUBViewControllerDefaultScrollHandler.m
- sources/HUBViewControllerFactoryImplementation.m
- tests/HUBLiveServiceTests.m
- tests/HUBViewControllerFactoryTests.m
- tests/HUBViewControllerTests.m
- tests/mocks/HUBViewControllerScrollHandlerMock.h
- tests/mocks/HUBViewControllerScrollHandlerMock.m
This change makes `HUBViewController` a concrete class (instead of an API protocol/implementation class pair) and exposes it as part of the public API. The initializer is still kept private (for now), since it relies on some dependencies being passed down from `HUBViewControllerFactory`.
This change is made to be more compatible with Swift, where currently `HUBViewControllerFactory` returns `UIViewController` as a type (for more info - see https://github.com/spotify/HubFramework/issues/158).
> Expose HUBViewController as a concrete class

- sources/HUBComponentReusePool.m
- sources/HUBComponentWrapper.h
- tests/HUBViewControllerTests.m
This fixes a bug that component wrapper's parent wrapper was not updated when component is reused, which led to inconsistency in visible views.
> Update components parent wrapper when it is reused

- include/HubFramework/HUBViewController.h
- sources/HUBViewController.m
- tests/HUBViewControllerTests.m
Extend HUBViewController delegate with a method that asks if we should ignore content insets for header component.
> Make it possible for body component to start behind header component.

- .travis.yml
Compatibility job using Xcode 7 still remains
Alternative to https://github.com/spotify/HubFramework/pull/172
> Use Xcode 8.1 for CI

- demo/sources/NavigationController.swift
- include/HubFramework/HUBViewController.h
- sources/HUBViewController.m
- tests/HUBViewControllerTests.m
Extend the delegete interface to notify when a component view is being reused to allow the delegate to clean up the view before it's being reused.
> Add HUBViewController delegate method for reused

- sources/HUBViewController.m
- tests/HUBViewControllerTests.m
🐞  This PR fixes following bug:
* `HUBContentOffsetObserver` is called if the content offset hasn’t been updated.
**How to reproduce**
1. Make the search bar in `GitHubFeature` in demo app a header component.
2. Hide the navigation bar.
3. Type sth in search bar.
**Current behaviour**
* Keyboard is hidden every time sth types one character.
**Expected behaviour**
* Keyboard is not hidden every time user types a letter.
**Final result after the fix**
> Bug: contentOffsetObserver is called if the content offset hasn’t been updated.

- include/HubFramework/HUBComponentFallbackHandler.h
Makes sure Swift implementors don’t get the force-unwrap of the types by default.
> Add missing nullability macros HUBComponentFallbackHandler.h

- Gemfile
- Gemfile.lock
This PR fixes the malformed PR comments from Danger by updating the 4.0.1 which contains a fix for the issue.
As a “good thing to do” it also updates Fastlane to ~> 1.100 bringing in many fixes since 1.106.
> Update to Danger 4.0.1 and Fastlane 1.110

- sources/HUBCollectionViewLayout.h
Seems to be a left over and couldn't find any other usage of the `HUBScrollBehaviorwrapper` class.
> Remove forward declaration of removed class

- sources/HUBComponentWrapper.m
- tests/HUBComponentWrapperTests.m
This patch fixes a bug that would leave gesture recognizers orphaned in their component wrapper’s superview, because they were never removed when the wrapper was deallocated.
> Remove a component wrapper’s gesture recognizer when it’s deallocated

- sources/HUBViewController.m
Fixes an issue with the `scrollToComponentOfType:...` method, where the callback would sometimes be called before the scrolling occured in cases where the component was already visible.
> Fix issue with scrolling method callback

- sources/HUBCollectionViewLayout.m
In HUBCollectionViewLayout computeForCollectionViewSize when the only
component requires adjustment we call updateLayoutAttributesForComponentsIfNeeded
on an unsigned int with lastComponent - 1, which is, big. This then calls
updateLayoutAttributesForComponents which goes in to a loop from 0 to a bajillion.
> Dont overflow during component adjustment

- demo/sources/HeaderComponent.swift
- demo/tests/HeaderComponentUITests.swift
- sources/HUBCollectionViewLayout.h
- sources/HUBCollectionViewLayout.m
- sources/HUBViewController.m
- sources/HUBViewModelRenderer.h
- sources/HUBViewModelRenderer.m
- tests/HUBCollectionViewLayoutTests.m
- tests/HUBViewControllerTests.m
- tests/mocks/HUBViewControllerScrollHandlerMock.h
- tests/mocks/HUBViewControllerScrollHandlerMock.m
Currently, when a header component is being used, the default behavior is to add top `contentInset` to account for its height. This brings some problems in non-Hub powered code, that can make assumptions about content inset that are no longer true. A more correct way of handling this (thanks @mhallendal for bringing this up!), would be to add proper top margin when we compute our `UICollectionViewLayout` - so that's what we now do!
A lot of tests were also making assumptions about `contentInset` that no longer are true, so those tests needed to be refactored to use component frames, insted of insets.
This is a step towards https://github.com/spotify/HubFramework/issues/181
> Add margin instead of content inset for header component

- HubFramework.xcodeproj/project.pbxproj
- tests/HUBCollectionViewLayoutTests.m
- tests/HUBViewControllerTests.m
- tests/utilities/HUBTestUtilities.h
Adds macro HUBAssertEqualFloatValues to replace XCTAssertEqualWithAccuracy as in #188.
Also adds HUBTestUtilities header for other reusable utilities functions for tests.
> Removes code duplication for asserting equality with accuracy

- HubFramework.xcodeproj/project.pbxproj
- include/HubFramework/HUBViewController.h
- sources/HUBComponentReusePool.h
- sources/HUBComponentReusePool.m
- sources/HUBViewController+Initializer.h
- sources/HUBViewController.m
- sources/HUBViewControllerFactoryImplementation.m
- tests/HUBViewControllerTests.m
- tests/mocks/HUBComponentReusePoolMock.h
- tests/mocks/HUBComponentReusePoolMock.m
This change refactors the way that the framework manages component wrappers, to make it more streamlined:
Current situation:
- `HUBViewController` creates component wrappers for root components itself.
- `HUBComponentReusePool` is used to create & reuse child components.
New situation:
- `HUBComponentReusePool` is used to manage all component wrappers.
While doing this, I uncovered a memory leak where header & overlay component wrappers would get retained by the framework even after they were no longer needed (this would last until their view controller would be deallocated). This has now been fixed, and a unit test for it has been added.
> Refactor the way component wrappers are managed (+ fix memory leak)

- live/sources/String+PrintWithColor.swift
A potential fix for #163. It simply appends a white Ansi color code when printing colored strings. This successfully restores the original terminal color.
I'm not sure how you would create a unit test for something like this, but would love to hear any suggestions.
> Fix colored strings to restore original terminal color

- include/HubFramework/HUBJSONSchemaRegistry.h
- sources/HUBJSONSchemaRegistryImplementation.m
- tests/HUBJSONSchemaRegistryTests.m
Was not yet implemented for some reason. All other registries offer an unregistration API, so makes sense for the JSON schema one to do so too.
> JSON schema registry: Add API for unregistering a custom schema

- documentation/Concept guide.md
This guide aims to provide an easy-to-navigate reference of all the concepts that the Hub Framework uses. Contains lightweight explanations of things like “View models” or “Components”.
> Add Concept Guide

- Dangerfile
There seems to be a bug in our Dangerfile ruby that leads to Danger failing and existing with a non-zero status. It appears it’s because `junit_report_path` is `nil` if the tests weren’t even ran. Which is the case if the license header check failed.
```
[21:18:35]: $ bundle exec danger
[21:18:37]: ▸ bundler: failed to load command: danger (/Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/bin/danger)
[21:18:37]: ▸ Danger::DSLError: 
[21:18:37]: ▸ [!] Invalid `Dangerfile` file: no implicit conversion of nil into String
[21:18:37]: ▸ #  from Dangerfile:37
[21:18:37]: ▸ #  -------------------------------------------
[21:18:37]: ▸ #    junit_report_path = Dir.glob(path + "/*TestSummaries.junit").first
[21:18:37]: ▸ >    if File.readable_real?(junit_report_path)
[21:18:37]: ▸ …
```
> Fix Danger choking on nil junit report path

- HubFramework.xcodeproj/project.pbxproj
- include/HubFramework/HubFramework.h
- Removes all extraneous overrides of build settings from the HubFramework library target.
- These are covered by our `spotify_os.xcconfig` file, so that we can override them internally.
- Some didn’t have any effect on the type of target so I removed them.
- Add two files which where missing from the umbrella header. Leading to warnings for users that imported the library as a clang module (e.g. apps in Swift, like the demo).
> Fix issues with building HubFramework in certain environments

- templates/xcode/Hub Framework/Cont operation + action observer.xctemplate/Swift/___FILEBASENAME___.swift
Argument was removed a while back, but we missed to update the template.
> Templates: Remove viewURI argument from HUBContentOperationActionObserver

- HubFramework.xcodeproj/project.pbxproj
- include/HubFramework/HUBDefaults.h
- include/HubFramework/HubFramework.h
- sources/HUBDefaultComponentFallbackHandler.m
- tests/HUBManagerTests.m
This change moves what was previously an inline string for the default component namespace (used when setting up the Hub Framework using the simplest convenience API) to a constant. It also adds a test to make sure that the constant is really used.
> Add constant for default component namespace + test it

- include/HubFramework/HUBViewControllerFactory.h
Before:
```swift
viewControllerFactory.createViewController(with:featureTitle:)
```
After:
```swift
viewControllerFactory.createViewController(withContentOperations:featureTitle:)
```
Using only `for:`, it’s not clear that the parameter refers to an array of content operations.
> Swift refinement: Tweak simplest API for creating a view controller

- documentation/Setup guide.md
The setup guide has been updated to recommend that the simplest initializer is used to setup `HUBManager`.
> Setup guide: Recommend the simplest way of setting up HUBManager

- demo/HubFrameworkDemo.xcodeproj/project.pbxproj
- demo/sources/CarouselComponent.swift
- demo/sources/ColorContainerComponent.swift
- demo/sources/DefaultComponentFactory.swift
- demo/sources/DefaultComponentNames.swift
- demo/sources/StickyHeaderContentOperation.swift
- demo/tests/SelectionUITests.swift
- include/HubFramework/HUBComponentWithChildren.h
- sources/HUBCollectionViewLayout.m
- sources/HUBComponentWrapper.m
- sources/HUBViewController.m
- tests/HUBViewControllerTests.m
This change makes the Hub Framework assume the responsibility of handling selection for child components, when those components were created through the framework (and not by using a custom `UIView`).
It’s become clear that it’s ambiguous (and very cumbersome) for each component to have to manually handle selection for its children. As long as we were mostly implementing containers (such as Carousels) as components with children, this was fine, as we could leverage nested `UICollectionViews` and `HUBComponentCollectionViewCell`. However, as we are creating more and more complex component hierarchies, with containers that add backgrounds and other fancy stuff - it started to become a problem.
So, with this change, parent components are no longer responsible for the selection of their …
> Automatically manage selection for child components

- include/HubFramework/HUBViewController.h
- sources/HUBViewController.m
- tests/HUBViewControllerFactoryTests.m
No good reason to keep it private, and it makes some operations that handle view URIs a lot simpler, since they can just access it from the view controller directly, instead of having to pass another parameter around.
> View controller: Make view URI a public property

- sources/HUBViewModelRenderer.m
The code was firing the completion to signal that it was done, and then updating internal state after. We should be updating our state before firing the completion.
We saw crashes where firing the completion could trigger an update, which would synchronously invoke another render - this meant that the start of the render method would be called again (reading an old `self.lastRenderedViewModel` and calculating a diff based on it) which would immediately be followed by the termination of the previous render method that would assign the correct object to `self.lastRenderedViewModel`. At this point, it was too late as the next invocation was already using an out-of-date object.
The would either manifest as a crash where:
- the collection view would be out of sync with the model at the end of …
> Don’t update state after calling the completion block.

- tests/HUBActionRegistryTests.m
- tests/HUBCollectionViewFactoryTests.m
- tests/HUBCollectionViewLayoutTests.m
- tests/HUBComponentGestureRecognizerTests.m
- tests/HUBComponentImageDataBuilderTests.m
- tests/HUBComponentModelBuilderTests.m
- tests/HUBComponentRegistryTests.m
- tests/HUBComponentTargetBuilderTests.m
- tests/HUBComponentWrapperTests.m
- tests/HUBDefaultImageLoaderTests.m
- tests/HUBFeatureRegistryTests.m
- tests/HUBIconTests.m
- tests/HUBInitialViewModelRegistryTests.m
- tests/HUBJSONSchemaRegistryTests.m
- tests/HUBLiveServiceTests.m
- tests/HUBViewControllerFactoryTests.m
- tests/HUBViewControllerTests.m
- tests/HUBViewModelBuilderTests.m
- tests/HUBViewModelLoaderFactoryTests.m
- tests/HUBViewModelLoaderTests.m
We need to make sure we `nil` all of our strong properties in the `tearDown` phase of unit tests.
*Errrr... Why?*
`XCTest` will create a new instance of your `XCTestCase` subclass for each test method in that class, and it will *not* release that test case for the lifetime of the tests being run. Maybe that's a bug in `XCTest`, or maybe it's by design. I'm not sure, but it's the way it's always been.
This means that any properties created during a test will never be released for us - `tearDown` is the only real opportunity we have to step in and release references to these instances.
*But why do we care during testing?*
- We want to test our `dealloc` methods too, right?
- Profiling unit tests is much more difficult when every property created in every test is still alive.
- If we ever …
> Memory management in tests

- include/HubFramework/HUBComponentWithSelectionState.h
Cells have automatic selection state handling, so no need to use the protocol for those.
> HUBComponentWithSelectionState: Remove doc comment about cells

- include/HubFramework/HUBViewControllerScrollHandler.h
- sources/HUBViewController.m
- sources/HUBViewControllerDefaultScrollHandler.m
- tests/HUBViewControllerTests.m
- tests/mocks/HUBViewControllerScrollHandlerMock.h
- tests/mocks/HUBViewControllerScrollHandlerMock.m
`UIScrollView`'s `keyboardDismissMode` is available since iOS 7 and is the preferred way for configuring the automatic keyboard dismissal. This option can reduce a lot of custom content offset observing code so less bugs and code duplication.
> Add ability to specify keyboardDismissMode by the scroll handler

- tests/HUBViewControllerTests.m
I've seen cases of a race condition where:
- `HUBViewControllerTests` invokes some logic that triggers an update in the collection view
- the test finishes and `tearDown` is called
- `tearDown` sets all the blocks in `HUBViewControllerTests` to `nil`
- a callback fired from the collection view which calls completion blocks and ultimately tries to call some of the `HUBViewControllerTests` blocks which are now `nil`.
Tests that invoke render methods should wait until the completion block has fired before finishing, but for now, this will deal with the issue.
> Check that blocks are not nil before calling them.

- include/HubFramework/HUBActionContext.h
- sources/HUBActionContextImplementation.h
- sources/HUBActionContextImplementation.m
- sources/HUBActionHandlerWrapper.m
- sources/HUBViewController+Initializer.h
- sources/HUBViewController.m
- sources/HUBViewControllerFactoryImplementation.m
- tests/HUBViewControllerTests.m
This change makes `HUBActionContext` carry a `HUBFeatureInfo` object that contains information about the feature that the action is being performed in. This was previously only exposed to content operations.
> Add feature info to HUBActionContext

- sources/HUBViewController.m
Previously, all image loading (even from cache) was forced to be async. The reason behind this was that we were using collection view cells to track what images belong to what component. But since a while back we’re now using component wrappers for that instead, which means that we can now allow some image loading to be synchronous (that’s up to `HUBImageLoader`).
This heavily reduces image flickering in view that are rapidly reloaded.
> View controller: Don’t force image loading to be async

- include/HubFramework/HUBViewController.h
- sources/HUBViewController.m
Exposes the HUBViewController's HUBActionPerformer protocol publicly in order to allow programmatic triggering of actions.
> Exposes the HUBViewController's HUBActionPerformer

- demo/sources/GitHubSearchResultsContentOperation.swift
- include/HubFramework/HUBJSONCompatibleBuilder.h
- sources/HUBComponentImageDataBuilderImplementation.m
- sources/HUBComponentModelBuilderImplementation.m
- sources/HUBComponentTargetBuilderImplementation.m
- sources/HUBJSONSchemaImplementation.m
- sources/HUBLiveContentOperation.m
- sources/HUBUtilities.h
- sources/HUBViewModelBuilderImplementation.m
- tests/HUBComponentImageDataBuilderTests.m
- tests/HUBComponentModelBuilderTests.m
- tests/HUBComponentTargetBuilderTests.m
- tests/HUBJSONSchemaTests.m
- tests/HUBViewModelBuilderTests.m
This PR resolves #232. More specifically it renames `-addJSONData:` to `-addJSONData:error:`, moving returned error to an out-parameter, instead returning a boolean success status. As well as renaming `-addDataFromJSONDictionary:` to `-addJSONDictionary:`
The methods where renamed to be more coherent and improve how they’re imported in Swift. This changes the addJSONData:error: method to now return its status and return the error via the passed in `NSError **`. Additionally the name of the methods is slightly tweaked when imported by Swift. As to make them read nicer. The methods will now import as follows in Swift:
```swift
public func addJSON(data: Data) throws
public func addJSON(dictionary: [String : Any])
```
As part of this change the `HUBAddJSONDataToBuilder()` function was …
> Rename methods in HUBJSONCompatibleBuilder for coherency and Swiftiness

- fastlane/Fastfile
Fastlane, just like Danger so might a Ruby thing, prints a warning if typographic quotation marks, apostrophes and so on are use. Even when used only in a comment…
This changes so that Fastlane won’t be sad anymore. Instead we’ll let humans reading the comments be sad 😢 Yes I’m sad right now 😢 
> Fix complaint about correct typography by Fastlane

- sources/HUBViewControllerDefaultScrollHandler.m
By mistake in my latest PR https://github.com/spotify/HubFramework/pull/243 I added some unused code, which I forgot to remove.
> Remove unused code introduced by mistake in previous PR.

- sources/HUBViewController.m
We register for `UIKeyboardWillShowNotification` and `UIKeyboardWillHideNotification` but only deregister for `UIKeyboardWillShowNotification` (twice).
> Corrects a typo when unregistering

- HubFramework.xcodeproj/project.pbxproj
- include/HubFramework/HUBComponentCategories.h
- include/HubFramework/HUBComponentLayoutTraits.h
- include/HubFramework/HUBErrors.h
- include/HubFramework/HUBHeaderMacros.h
- include/HubFramework/HubFramework.h
- sources/HUBDefaultImageLoader.m
- sources/HUBErrors.m
- sources/HUBUtilities.h
This PR makes the helper `HUBAddJSONDataToBuilder()` function safer and reworks how we create errors.
This makes adding JSON data to a `HUBJSONCompatibleBuilder` safer. Since we’ll make sure `nil` isn’t passed to an Apple API that doesn’t support it.
Basically the Objective-C compiler is so easy to trick about nullability we’ve observed places where `nil` was passed to `addJSONData:error:`. This change makes sure we catch that before sending nil to an Apple owned API parameter that is marked as nonnull. Better safe than sorry eh 😅
This changes all errors to use a domain and code.
The standard Cocoa way of creating errors is to create an error domain that groups errors belonging together. The domain should not be used to identify _specific_ errors, as was done before this PR. Instead the …
> Make HUBAddJSONDataToBuilder() safer and rework error creation

- HubFramework.xcodeproj/project.pbxproj
- sources/HUBOperation.h
- sources/HUBOperation.m
- sources/HUBOperationQueue.h
- sources/HUBOperationQueue.m
- sources/HUBViewController.m
- tests/HUBOperationQueueTests.m
This is the first in a series of tasks to make more code in the Hub Framework operation oriented.
We’ve run into a lot of issues during the last couple of months due to state management, where things have become out of sync or required even more state to be introduced. For example, when interfacing with `UICollectionView`, which is very asynchronous, we could end up with inconsistent states because we would update our models too early or too late.
Operations make this a lot simpler, since using a central queue that all events pass through, you can make more assumptions (and IMO, reason about it easier) about in what sequence various events and bodies of work will occur.
Now, instead of having to keep state like `pendingViewModel` and `isRendering`, `HUBViewController` now has an operation …
> View controller: Make rendering code operation oriented

- HubFramework.xcodeproj/project.pbxproj
- include/HubFramework/HUBViewControllerDefaultScrollHandler.h
- include/HubFramework/HubFramework.h
This PR is a fixed version of #230. The problem with the initial PR was that it didn’t mark the header as _public_ for the framework. As such it didn’t build. Given an error about “duplicate module map”.
Since it’s a new PR I opted to rebase away the original merge with `master` commits.
Original description from @nataliq in #230:
> Moves the `HUBViewControllerDefaultScrollHandler` to the include folder so that it could be subclassed by features that want to provide different implementation just for few methods. Apart from that only the description of the class is slightly modified.
> Expose the default scroll handler as a override point [fixed]

- sources/HUBViewController.m
That code was probably a workaround for some issue but it is not covered by any tests and there are no comments. Given the fact that it has side effects causing bugs (if the collection view is scrolled to a specific position when the content insets change, the content offset will be reset) it is better if this code is removed.
> Remove code that is reseting the content offset when insets change

- tests/mocks/HUBComponentLayoutManagerMock.m
`CGFloat` is a float on 32-bit architectures.
> Allow tests to compile on 32 bit

- tests/HUBComponentWrapperTests.m
Setting an object to `nil` doesn't guarantee that `dealloc` will be called on the same runloop (especially on older 32-bit architectures).
Use an `@autoreleasepool` to guarantee this.
> Use an autoreleasepool to guarantee deallocation

- sources/HUBComponentCollectionViewCell.m
The way Hub Framework wrapped the view of components caused UIKit to run into unsatisfiable constraints. This affects all constraint based views that had internal margins. For example 8 points from the top and bottom. Since the view wasn’t given a size, and the autoresizing mask said it couldn’t be resized automatically, such constraints would require the view to “implode” (top edge 8 points _below_ the view and the bottom edge 8 points _above_ the view). I.e. an impossible layout.
It would also result in the following message being printed to (or rather filling up) the console. As well as hitting the `UIViewAlertForUnsatisfiableConstraints` symbolic breakpoint (everyone should be running that one 😉).
```
2016-12-22 15:36:41.493646 S4A[14387:9231016] [LayoutConstraints] Unable to …
```
> Fix Hub Framework causing unsatisfiable constraints

- tests/HUBComponentModelTests.m
While we decide the best way to assert for object equivalence over at https://github.com/spotify/HubFramework/pull/259, we should fix the cases that are causing tests to fail on 32-bit systems (i.e. the `NSIndexPath` case).
For info, using instance equality (i.e. `==` ) on 2 "equivalent" instances will work on 64 bit architectures (with tagged pointers) but not on 32 bit architectures.
> Don’t use XCTAssertEqual for NSIndexPath equivalence.

- demo/tests/HeaderComponentUITests.swift
This was initially inside my tvOS PR but it will take some time for that one to be fixed and merged.
I cherrypicked it into this separate PR so we can act quicker. 
Fixes https://github.com/spotify/HubFramework/issues/264
> Fix testCollectionViewContentInsetEqualToHeaderHeight

- tests/HUBViewControllerTests.m
Replaces https://github.com/spotify/HubFramework/pull/256
@JohnSundell asked me to squash the changes and I kinda screwed up my branch, so I've applied this again to another PR.
There are no changes since the last review.
> Add test for content operation and render overlap

- sources/HUBViewController.m
In the iOS client, we have a tab bar controller which has a navigation controller as its root VC. There is a Hub VC as the root VC of this navigation controller and this is currently the active VC. We're seeing a crash when tapping the tab bar item for a VC that's already the active tab. The scenario is outlined below:
- A content operation runs, and generates a view model with (e.g.) 20 body component models. The Hub VC renders these and the internal UICollectionView creates cells for index paths 0-0, 0-1 and 0-2 (for example). 
- We navigate from this VC to a new VC (B) and wait for that to render.
- We then tap the active tab bar to invoke the standard OS behaviour to pop to the root VC in the navigation controller.
- As VC B is being popped, a content operation runs again inside VC A …
> Use the same logic as the renderer to prevent a crash

- documentation/Architectual overview.md
This document is aimed at developers who are looking to contribute to the Hub Framework, and want to get a more in-depth understanding of how the internals work, and what patterns that were chosen (and why).
The document is currently incomplete, but still offers some value (so pushing it up now for handover purposes). More work needs to be done to cover all aspects of the framework (with “Hubs sessions” and the other documentation being complementary to this document).
> Add first draft of an “Architectural overview”

- sources/HUBComponentCollectionViewCell.m
In some case we’d still lay the cell’s view out with a `.zero` size. The problem occurred before the cell had a chance to resize the hosted view. This PR fixes the problem by making sure the view gets an initial size, so that no resize is required.
> Fix some auto-layout breakages

- sources/HUBViewModelDiff.h
- sources/HUBViewModelDiff.m
- sources/HUBViewModelRenderer.m
- tests/HUBViewModelDiffTests.m
When we calculate a diff and there are no changes, we don't need to spend time reloading the collection view, either with `reloadData` or `performBatchUpdates:completion:`. These methods are already called too often and have been linked to crashes under certain conditions where we update content operations frequently. After I applied this patch, I didn't see any crashes under those same conditions.
The `HUBViewModelRenderer` patch is quite hard to follow, so here's a summary of what I did:
- Created a new `renderViewModel:inCollectionView:usingBatchUpdates:addHeaderMargin:completion:` method (i.e. the same as the existing method but without the `animated:` parameter.
- In the original method (with `animated:`, we now call the new method in a block, either directly (if we are animating), …
> Don’t reload the collection view if there is nothing in the diff.

- sources/HUBViewController.m
`self.registeredCollectionViewCellReuseIdentifiers` was being set up and checked for an existing cell reuse identifier, but we never added the identifier to the collection to stop us registering multiple times.
> Don’t register multiple times

- sources/HUBComponentWrapper.h
- sources/HUBComponentWrapper.m
- sources/HUBViewController.m
When the `HUBViewController` creates a cell, it creates the correct component for that cell and calls `configureViewWithModel:containerViewSize:` on that component, which can use this information to create a component-specific layout that takes the parent size into consideration.
However, when the VC is rotated / the VC is resized in other ways, there's no opportunity to recalculate that layout with the new parent size information.
This PR addresses this by forwarding this information to all component wrappers currently being displayed by the view controller's collection view.
> Support components having different layouts on rotation.

- sources/HUBViewController.m
Setting the view model and collection view to `nil` under low memory conditions doesn't seem like a very safe thing to do. We're seeing crashes because:
-  collection views are reporting that they don't have a reuse identifier registered 
- collection views are reporting discrepancies between models and cells currently visible
Both could be caused by a collection view / view model being set to `nil` and recreated at some point in the middle of an important operation.
Let's try removing the `didReceiveMemoryWarning` implementation and see if we see a reduction in crash reports.
> Don’t discard important objects in low memory conditions

- sources/HUBComponentCollectionViewCell.m
**tl;dr** Subclasses of `UICollectionReusableView`, and especially subclasses of e.g. `UICollectionViewCell`, should message super in `-prepareForReuse`.
---
The implementation of `-prepareForReuse` is documented in as part of `UICollectionReusableView` and it states that the method doesn’t do anything. So it should be safe to not message super, right Not really. The API docs does recommend that subclasses messages super anyhow.
> The default implementation of this method does nothing. However, when overriding this method, it is recommended that you call super anyway.
Further the documentation notes that subclasses, such as, `UICollectionViewCell` overrides the method to perform relevant actions. Since `HUBComponentCollectionViewCell` subclasses `UICollectionViewCell` it _must_ message …
> Fix not messaging super in -prepareForReuse

- documentation/Setup guide.md
Probably meant CFBundleURLTypes and not CGBundleURLTypes :)
> Fix Typo in Setup Guide Documentation (Info.plist file)

- sources/HUBCollectionView.h
- sources/HUBCollectionView.m
- sources/HUBViewController.m
As noticed in #280 the registry that keeps track of registered reuse identifiers need to be better tied to the collection view. This makes it a property of `HUBCollectionView` which means that whenever we recreate the collection view in `HUBViewController` the registry will be recreated as well.
@spotify/objc-dev @cerihughes
> Tie cell class register to collection view.

- sources/HUBViewModelDiff.h
- sources/HUBViewModelDiff.m
- sources/HUBViewModelRenderer.m
- tests/HUBViewModelDiffTests.m
- tests/utilities/HUBViewModelUtilities.h
- tests/utilities/HUBViewModelUtilities.m
Account for changes of header component model.
Supplements PR https://github.com/spotify/HubFramework/pull/277 ( Don’t reload the collection view if there is nothing in the diff. )
Core of the change logic in `HubViewModelRenderer` :  "When header changes, do reload"
```objc  
BOOL const hasDiffChanges = (diff == nil || diff.hasBodyChanges || diff.hasHeaderChanges);
```
Added property `hasHeaderChanges` to HUBViewModelDiff class
Renamed property `hasChanges` to `hasBodyChanges` to be more specific
Added test cases for basic header changes
Expanded helper methods in  HUBViewModelUtilities.m to for creating header component easily
> HubViewModelRenderer: Add simple check for Header changes to diffing

- sources/HUBViewController.m
On rotation, we trigger a call to `[HUBComponentWrapper configureViewWithModel:containerViewSize:]`. This configures the cell to show the placeholder icon but doesn't reload the image.
Some components (e.g. the hugs carousel) will trigger a reload of images in all of its children at this point, but come components (e.g. the hugs entity card) don't. We should trigger a reload of components that support images at this point too.
> Trigger a load of images on rotation

- sources/HUBComponentWrapper.m
> Enables UISegmentedControl touch

- sources/HUBCollectionViewLayout.m
The implementation of `layoutAttributesForElementsInRect:` produces several duplicates instances of `UICollectionViewLayoutAttributes`. Rewrote this implementation to just check frame intersections and in the tests that I ran, it produced exactly the same results but without duplication.
Removing this also allowed us to remove other private methods that are no longer needed.
> Don’t track indexPathsByVerticalGroup

- sources/HUBViewModelLoaderImplementation.m
- tests/HUBViewModelLoaderTests.m
If connectivity state updates before the viewmodel has been explicitly
loaded (i.e. its viewcontroller has appeared) then it might be loaded
unnecessarily at this point simply by being initialized.
Fixed by only observing connectivity after the point the view model
should be loaded.
> Delay observing of connectivity state

- include/HubFramework/HUBViewModelLoader.h
- sources/HUBViewController+Initializer.h
- sources/HUBViewController.m
- sources/HUBViewModelLoaderImplementation.h
- sources/HUBViewModelLoaderImplementation.m
The HUBViewController was passed a concrete implementation of HUBViewModelLoader instead of the protocol which tightly couples it to the implementation.
This allows for a separate view model loader to be implemented (or passed in by the user of the framework).
I didn't want to expose the action performer on the HUBViewModel which is why the view controller checks for conformance to an internal subprotocol to HUBViewModelLoader.
> Remove coupling of HUBViewController and HUBViewModelLoaderImpl

- .gitignore
- live/Makefile
- live/Package.swift
Hi everybody! 👋 Guess who's back? 😜
Played around a bit with Hubs & live editing again tonight, and realized we can make the command line tool for live editing a lot easier to install. This change makes `hublive` buildable using the Swift Package Manager, and installable through Make.
Instead of having users open and archive the Xcode project and manually move the built binary, `make` can now simply be run in the `live` folder, resulting in it being built using `swift build` and moved to `/usr/local/bin`.
> Live: Enable easier building & installation with SPM & Make

- README.md
With master starting to work towards 3.x it's better for external users to use 2.x until we have a better idea for what the 3.x API will look like.
@spotify/objc-dev @cerihughes
> Specify to use 2.x branch for Carthage users

- include/HubFramework/HUBViewControllerScrollHandler.h
- sources/HUBViewControllerDefaultScrollHandler.m
- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerImplementationTests.m
- tests/mocks/HUBViewControllerScrollHandlerMock.h
- tests/mocks/HUBViewControllerScrollHandlerMock.m
We need to observe content offset changes inside a hub view controller and it currently doesn't implement a didScroll method. This PR adds one.
> Scroll Handler: add did scroll method

- sources/HUBFeatureRegistration.m
Fixes some code that was introduced in https://github.com/spotify/HubFramework/pull/308 and caught in review after the merge.
> Copy the parameter as it has a copy attribute on the property.

- demo/tests/HeaderComponentUITests.swift
The behaviour of `XCUIElement`'s `swipeUp` and `swipeDown` methods seems to have changed with iOS10.3 (swipes now seem to stop when a cell is completely on screen and don't decelerate).
To make sure our swiping tests work between versions, I've rewritten them to swipe until the desired header height is reached. They'll then swipe once more to make sure the bounce happens, and the height settles back to the desired height after the bounce.
If the expected height hasn't been reached by 20 swipes, the test fails (as before).
_Note_: Can someone validate my Swift method naming - I'm still making the transition ;)
> Rewrite swipe tests to not count swipes

- include/HubFramework/HUBViewController.h
- sources/HUBViewControllerExperimentalImplementation.m
- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerImplementationTests.m
We removed the code that released the collection view on low memory. It makes sense to have a single point of creation for the view again as it simplifies the VC.
I've also removed the configuration of the `bounce` property. It's currently never set to anything other than the default. I'll work on a PR that exposes the view through the API, so clients can set things directly on the view in future - this will mean that we don't have to write so much "pass through" code.
> Always create collection view in load view

- HubFramework.xcodeproj/project.pbxproj
- demo/sources/AppDelegate.swift
- include/HubFramework/HUBContainerView.h
- include/HubFramework/HUBViewController.h
- include/HubFramework/HubFramework.h
- sources/HUBCollectionContainerView.h
- sources/HUBCollectionContainerView.m
- sources/HUBContainerView.m
- sources/HUBViewController.m
- sources/HUBViewControllerExperimentalImplementation.m
- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerImplementationTests.m
This PR:
- Simplifies the `HUBContainerView` API to just declare a "content view" as a `readonly` `UIScrollView`
- Exposes `HUBContainerView` through the public API via the `HUBViewController`
- Takes all `UIScrollView`-specific pass-through logic out of the VCs. Clients should directly modify the the view's contentView now.
- Internally, we use `HUBCollectionContainerView` as the `UICollectionView`-specific subclass of `HUBContainerView`. We can move more `UICollectionView`-specific code into this subclass in future PRs.
Note: This is an API breaking change.
> Expose container view through API

- sources/HUBSingleGestureRecognizerSynchronizer.m
- sources/HUBViewControllerExperimentalImplementation.m
- sources/HUBViewControllerImplementation.m
The logic to stop multiple gesture recognizers where a bit flawed. When a recognizer was told to not recognize it would immediately reset the state of the synchronizer. Such that the next recognizer would be able to recognize. Even if the original recognizer hadn’t stopped recognizing. We now compare the finished gesture recognizer with the one that began handling the gesture. Only if it’s the same do we reset it; allowing another one to recognize.
Both the collection view and our custom selection logic was firing. This could cause a component to stay selected visually until the view was interacted with again. As such `allowsSelection` has been set to `NO` allowing HubFramework to do its custom selection and highlighting management.
> Fix duplicate selection logic

- sources/HUBViewControllerExperimentalImplementation.m
- sources/HUBViewControllerImplementation.m
This PR removes `componentWrappersByIdentifier` which is not used anywhere.
> Remove unused componentWrappersByIdentifier 

- sources/HUBComponentModelBuilderImplementation.m
- sources/HUBComponentModelImplementation.m
- sources/HUBComponentReusePool.m
- sources/HUBOperation.h
- sources/HUBOperation.m
- sources/HUBViewControllerExperimentalImplementation.m
- sources/HUBViewControllerImplementation.m
- tests/HUBOperationQueueTests.m
Ran the project through [Infer](http://fbinfer.com) and cleaned up the errors and warnings.
Not sure if this is an Infer quirk or not, but it seemed to complain about block params being nullable, even when `nonnull` is assumed.
Better safe than sorry I suppose ¯\\\_(ツ)\_/¯ 
The following is the Infer CSV report:
```csv
class,kind,type,qualifier,severity,line,procedure,procedure_id,file,trace,key,qualifier_tags,hash,bug_id,always_report,advice
,WARNING,PARAMETER_NOT_NULL_CHECKED,"Parameter `completionHandler` is not checked for null, there could be a null pointer dereference: pointer `completionHandler` could be null and is dereferenced at line 38, column 9",MEDIUM,38,"__objc_anonymous_block_HUBOperation_synchronousOperationWithBlock:______1","__objc_anonymous_block_HUBOperation_synchronous …
```
> Fix warnings from Infer

- documentation/Action programming guide.md
- documentation/Layout programming guide.md
Simple edits. The Action Programming Guide had an old method, causing confusion when attempting to implement actions in a step-by-step fashion. Action Programming Guide tells new users to extend HUBComponentLayoutTraits but doesn't show how to do it. Added an example.
> Documentation enhancements

- sources/HUBViewControllerExperimentalImplementation.m
- sources/HUBViewControllerImplementation.m
- tests/HUBViewControllerImplementationTests.m
The wrong argument is sent to the following HUBCollectionViewDelegate method:
```
- (void)collectionView:(UICollectionView *)collectionView
didEndDisplayingCell:(UICollectionViewCell *)cell
forItemAtIndexPath:(NSIndexPath *)indexPath
```
Instead of `HUBComponentCollectionViewCell` we should send a view from the component wrapper.
> Bug: wrong argument is sent to HUBCollectionViewDelegate method

- sources/HUBAutoEquatable.m
Property lists must be freed manually.
> Fix memory leak in HUBAutoEquatable

- .travis.yml
We don’t officially support building with Xcode 7 anymore.
> Remove Xcode 7 CI job

- sources/HUBComponentWrapper.m
Will be set to the component instance’s identifier. To make it easier to find Hub components in UI tests.
@spotify/objc-dev @mumme
> Set accessibility identifier by default

- sources/HUBConfig.m
I don’t think this class actually works, but having these global variables shadowing ivars can’t possibly help.
@cerihughes
> Fix accidental global variables

- sources/HUBSelectionAction.m
We don’t want to change the deployment target post-deprecation, but we can avoid the visible warning.
> Suppress iOS 10 SDK deprecation warning
